Closes #141
hpi-swa-lab/BP2021RH1 pull request #148
Opened 2022-11-02 13:03 UTC by rheaSPK

<img width="481" alt="image" src="https://user-images.githubusercontent.com/28736098/199496654-c6e59949-8c63-4418-a004-425fd2316973.png">

2022-11-03 14:38 UTC, olschulz requested changes
Tests

2022-11-08 08:51 UTC, rheaSPK commented
Added tests, is there a need for limiting the Badge count to a certain number (99+)?

2022-11-12 10:56 UTC, baerlach-git commented on projects/bp-gallery/src/components/views/picture/sidebar/comments/CommentsContainer.tsx
> +    return role < AuthRole.CURATOR
Wofür sind diese Zeilen nötig? Warum kann nicht grundsätzlich einfach comments?.length ausgegeben werden?

2022-11-12 10:57 UTC, baerlach-git approved these changes
W

2022-11-12 11:01 UTC, olschulz approved these changes
Top!

2022-11-12 11:04 UTC, olschulz commented on projects/bp-gallery/src/components/views/picture/sidebar/comments/CommentsContainer.tsx
> +    return role < AuthRole.CURATOR
Die Elemente die kein publishedAt haben sind bis jetzt pending bzw unapproved kommentare und die sollten für einen normalen nutzer nicht angezeigt werden

2022-11-13 08:21 UTC, merged