Bild des tages
hpi-swa-lab/BP2021RH1 pull request #224
Opened 2023-01-19 10:34 UTC by rheaSPK

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/28736098/213419585-828effc6-d10d-4893-9564-a7a28c93104a.png">

Closes #214 

PS: Design is suboptimal, if you have a better idea, draw a design prototype. This is the best I can do with the current design prototype

2023-01-20 16:17 UTC, baerlach-git approved these changes
sollte passen

2023-01-21 19:15 UTC, rheaSPK commented on .gitignore
> +.env.development
Well I did change .env.development in order to use my local strapi instance. And ofc you’re right with .env

2023-01-21 19:24 UTC, rheaSPK commented on projects/bp-gallery/src/components/views/start/WeeklyPicture.tsx
> +        />
I did implement it accordingly to the PictureGrid-Implementation, but I can change that

2023-01-23 15:22 UTC, olschulz commented on .gitignore
> +.env.development
Es gibt auch .env.development.local

2023-01-24 10:49 UTC, DavidSchroschk commented on projects/bp-gallery/src/graphql/operation.graphql
> +              formats
Musst du dann nicht an allen Stellen wo getPictureInfo verwendet wird die verwendeten Types anpassen bzw. können da nicht Fehler passieren wenn z.B. formats = null?

2023-01-24 12:04 UTC, DavidSchroschk commented on projects/bp-gallery/src/components/views/start/DailyPicture.tsx
> +      setIsFocussed(true);
```suggestion
      setIsFocused(true);
```

2023-01-24 12:05 UTC, DavidSchroschk commented on projects/bp-gallery/src/components/views/start/DailyPicture.tsx
> +    [setIsFocussed]
```suggestion
    [setIsFocused]
```

2023-01-24 12:06 UTC, DavidSchroschk commented on projects/bp-gallery/src/components/views/start/DailyPicture.tsx
> +      {isFocussed && picture && (
```suggestion
      {isFocused && picture && (
```

2023-01-24 12:06 UTC, DavidSchroschk commented on projects/bp-gallery/src/components/views/start/DailyPicture.tsx
> +              setIsFocussed(false);
```suggestion
              setIsFocused(false);
```

2023-01-24 12:09 UTC, DavidSchroschk commented on projects/bp-gallery/src/components/views/start/DailyPicture.tsx
> +  const weeklyPictureId = choosePictureId(pictureIds);
```suggestion
  const dailyPictureId= choosePictureId(pictureIds);
```

2023-01-24 12:10 UTC, DavidSchroschk commented on projects/bp-gallery/src/components/views/start/DailyPicture.tsx
> +  const { data } = useGetPictureInfoQuery({ variables: { pictureId: weeklyPictureId } });
```suggestion
  const { data } = useGetPictureInfoQuery({ variables: { pictureId: dailyPictureId } });
```

2023-01-24 12:14 UTC, DavidSchroschk requested changes
Grundsätzlich top. An einigen stellen steht noch Weekly statt Daily und focused bitte mit einem 's' :)

2023-01-28 10:42 UTC, rheaSPK commented on projects/bp-gallery/src/graphql/operation.graphql
> +              formats
Ich denke das Format ist bei allen Bildern automatisch dabei und falls nicht, wird das Bild halt nicht angezeigt. Ich gehe nicht davon aus, dass `getPictureInfo` an anderen Stellen Probleme bereitet, weil dort dann halt einfach nicht das Format gebraucht wird

2023-01-28 11:52 UTC, DavidSchroschk approved these changes

2023-01-28 16:28 UTC, merged