303 pictures in the uploadarea should be sortable via drag and drop
hpi-swa-lab/BP2021RH1 pull request #304
Opened 2023-03-13 18:51 UTC by olschulz

Closes #303

I still don't know how react droppable decides the file order upon dropping them, it seems to be completely random and also changes when trying it multiple times. At the moment I just sort the files alphabetically so that there's atleast some order.

2023-03-14 09:30 UTC, rheaSPK submitted a review, later dismissed
Gerade werden die Bilder genau anders herum hochgeladen wie ich das erwarten würde. Wenn ich ein Bild mit [1] [2] anordne, wird es hinterher [2][1] angezeigt. Das ergibt Sinn, weil die Bilder absteigend sortiert werden, aber ich würde erwarten, dass meine Sortierung  auch so angezeigt wird

2023-03-14 09:43 UTC, olschulz commented
> Gerade werden die Bilder genau anders herum hochgeladen wie ich das erwarten würde. Wenn ich ein Bild mit [1] [2] anordne, wird es hinterher [2][1] angezeigt. Das ergibt Sinn, weil die Bilder absteigend sortiert werden, aber ich würde erwarten, dass meine Sortierung auch so angezeigt wird

Jo das ist mir auch schon aufgefallen, war mir nur sehr unsicher ob wir den Upload wirklich nach den Neuerscheinungen sortieren sollen, da dann in Zukunft bei eventuellen anderen Sortierungen das erste hochgeladene Bild die letzte ID hat

2023-03-19 17:00 UTC, MariusDoe requested changes
Some small problems with the id/key and some other minor things :)

2023-03-21 13:15 UTC, baerlach-git requested changes
maybe rethink using the file names for sorting?

2023-03-21 22:10 UTC, olschulz commented on projects/bp-gallery/src/components/common/picture-gallery/PictureUploadArea.tsx
> +              <SortableItem id={file.file.name} key={`${file.file.name}-${index}`}>
Should be fixed now

2023-03-22 12:14 UTC, MariusDoe approved these changes

2023-03-22 13:50 UTC, baerlach-git approved these changes
schönet Ding

2023-03-23 14:29 UTC, merged