363 Bild Statistiken
hpi-swa-lab/BP2021RH1 pull request #383
Opened 2023-03-17 13:11 UTC by olschulz

Closes #363

2023-03-19 16:25 UTC, MariusDoe requested changes
I have annotated views I'm not sure should have the stats. In addition, I think the `LatestPicturesView` should have them.

Regarding styling, I have made some changes on [`363-pfactz-more-styling`](https://github.com/hpi-swa-lab/BP2021RH1/tree/363-pfactz-more-styling). If you like them, you can merge them into here. Otherwise, please tell me why you don't like them ;)

Other than that, nice work!

2023-03-19 16:25 UTC, MariusDoe commented on projects/bp-gallery/src/components/views/bulk-edit/BulkEditView.tsx
> +                <ShowStats>
Not sure we want this here as it is a Curator-only view.

2023-03-19 16:25 UTC, MariusDoe commented on projects/bp-gallery/src/components/views/uploads/UploadsView.tsx
> +          <ShowStats>
Not sure either. However, I think one could argue that it feels more natural than in BulkEdit here. Still, I'm not sure we want Stats inside Curator-only views.

2023-03-22 12:23 UTC, MariusDoe approved these changes
I like

2023-03-22 12:59 UTC, DavidSchroschk approved these changes
👍 1 💬 "Nice"

2023-03-22 13:17 UTC, merged