501 custom overview inhaltsauswahl
hpi-swa-lab/BP2021RH1 pull request #504
Opened 2023-05-16 13:02 UTC by LinoH5

- Allows multiple overviews in one component, to select them via tabs
![custom-selection-decades](https://github.com/hpi-swa-lab/BP2021RH1/assets/64465748/98410889-8929-48a5-807f-261d033468c9)
![custom-selection-images](https://github.com/hpi-swa-lab/BP2021RH1/assets/64465748/e128f93c-4aa9-488a-87a7-42e04a8c5946)

- Nebeneffekt: (Vielleicht gar nicht so schlimm)
![clipboard-neu](https://github.com/hpi-swa-lab/BP2021RH1/assets/64465748/67f1fccd-1e45-4c91-9291-31f81d9c2392)

2023-05-17 09:48 UTC, ole1711 commented on projects/bp-gallery/src/components/common/OverviewContainer.tsx
> +  const childrenArray = Children.toArray(children);
Apparently using Children is uncommon and can lead to fragile Code: [source](https://react.dev/reference/react/Children)

2023-05-17 09:48 UTC, ole1711 commented on projects/bp-gallery/src/components/common/PictureOverview.scss
why no tailwind? :c

2023-05-17 09:48 UTC, ole1711 commented on projects/bp-gallery/src/components/common/TagOverview.tsx
> +    const initialState = calculateMaxCategoriesPerRow((ref.current?.clientWidth ?? 0) as number);
Since you don't do anything with the initialState, you can just immediately return the expression instead of saving it as a const.

2023-05-17 14:29 UTC, ole1711 approved these changes
leider immernoch kein Tailwind aber naja ich lasse es mal durchgehen

2023-05-19 13:44 UTC, olschulz requested changes
Finde die neue Bildgröße bei den Clipboard und den verlinkten Texten usw gar nicht so schlimm :)

2023-05-19 13:44 UTC, olschulz commented on projects/bp-gallery/src/components/common/TagOverview.tsx
> +    setRowLength(calculateMaxCategoriesPerRow((ref.current?.clientWidth ?? 0) as number));
see above

2023-05-19 13:44 UTC, olschulz commented on projects/bp-gallery/src/components/common/PictureOverview.scss
> +}
![image](https://github.com/hpi-swa-lab/BP2021RH1/assets/64468276/9ac0be45-4a4d-4281-a9ab-bc7b49a1b66c)

2023-05-22 14:29 UTC, olschulz approved these changes
Elefantastisch!

2023-05-23 09:46 UTC, merged