move picture id count calculation to own component per archive
hpi-swa-lab/BP2021RH1 pull request #514
Opened 2023-05-17 15:38 UTC by olschulz

Quick Fix that Closes #513 

Maybe instead calculate picture counts with own strapi graphql resolver?

2023-05-19 13:19 UTC, ole1711 approved these changes
bei mir dauert es jetzt ein paar sekunden (5-10s ca), bis fürs ahrens archiv der picture count angezeigt wird, die anderen sind aber sofort da. aber no biggie, wenigstens kann man jetzt direkt aufs archiv klicken.

2023-05-22 12:02 UTC, olschulz commented
> bei mir dauert es jetzt ein paar sekunden (5-10s ca), bis fürs ahrens archiv der picture count angezeigt wird, die anderen sind aber sofort da. aber no biggie, wenigstens kann man jetzt direkt aufs archiv klicken.

Es sollten jetzt alle picture counts quasi sofort auftauchen und der lag am anfang sollte auch größtenteils weg sein

2023-05-22 16:41 UTC, rheaSPK approved these changes

2023-05-23 11:19 UTC, ole1711 requested changes

2023-05-23 11:19 UTC, ole1711 commented on projects/bp-strapi/src/index.ts
> +              console.log(ctx.state);
???

2023-05-23 13:27 UTC, olschulz commented on projects/bp-strapi/src/index.ts
> +              console.log(ctx.state);
!!!

2023-05-24 00:30 UTC, merged