495 add growthbook javascript sdk for bp strapi
hpi-swa-lab/BP2021RH1 pull request #527
Opened 2023-05-24 11:38 UTC by DavidSchroschk

2023-05-25 09:40 UTC, MariusDoe requested changes

2023-05-25 09:40 UTC, MariusDoe commented on projects/bp-gallery/src/helpers/app-helpers.ts
> +      experimentData?.map((experiment: { experimentId: string; variationId: string }) => {
since you don't use the result, I think `forEach` is more appropriate than `map`

2023-05-25 09:40 UTC, MariusDoe commented on projects/bp-strapi/src/middlewares/growthbook-client.ts
> +  // Add your own logic here.
maybe remove the copy-pasted comment? 😄

2023-05-25 09:40 UTC, MariusDoe commented on projects/bp-strapi/src/middlewares/growthbook-client.ts
> +    ctx.state.withGrowthBook = (theCtx, f) => {
is this called anywhere? if not, how does the `trackingCallback get its `currentCtx`?

2023-05-25 11:01 UTC, olschulz requested changes

2023-05-25 19:51 UTC, olschulz approved these changes
Elefantastisch!

2023-05-26 10:33 UTC, MariusDoe commented on projects/bp-strapi/src/middlewares/growthbook-client.ts
> +    ctx.state.withGrowthBook = (theCtx, f) => {
This PR just lays the foundational API for future work with experiments. That's why `withGrowthBook` is called nowhere (yet).

2023-05-26 10:34 UTC, MariusDoe approved these changes

2023-05-26 11:07 UTC, merged