288 use mui theme for coloring buttons
hpi-swa-lab/BP2021RH1 pull request #551
Opened 2023-06-14 11:24 UTC by MariusDoe

Closes #288

2023-06-14 12:47 UTC, DavidSchroschk approved these changes

2023-06-14 14:43 UTC, ole1711 commented on projects/bp-gallery/src/shared/style.module.scss
> +$likeColor: rgb(96 165 250); // blue-400 from tailwind
can we change this to #60A5FA ? I think it's better if the colours are all in Hex :)

2023-06-14 14:51 UTC, ole1711 requested changes

2023-06-14 14:51 UTC, ole1711 commented on projects/bp-gallery/src/shared/style.module.scss
> +$likeColor: rgb(96 165 250); // blue-400 from tailwind
can we change this to #60a5fa ? I think it's better if the colours are all in Hex :)

2023-06-15 08:11 UTC, ole1711 approved these changes

2023-06-15 08:11 UTC, merged