570 add support for setting coordinates for location tags
hpi-swa-lab/BP2021RH1 pull request #571
Opened 2023-06-21 22:38 UTC by LinoH5

- Allow Curators to set coordinates for each location tag, via a map in the `LocationManagementDialog`

2023-06-22 12:09 UTC, ole1711 commented on projects/bp-gallery/src/components/views/location-curating/LocationEntry.scss
> +          overflow: auto;
wo tailwind

2023-06-22 12:27 UTC, ole1711 approved these changes

2023-06-22 15:23 UTC, MariusDoe requested changes

2023-06-22 15:23 UTC, MariusDoe commented on projects/bp-gallery/src/components/views/location-curating/LocationEntryActions.tsx
> +        <IconButton>{<LocationOn className='text-[#446ab7]' />}</IconButton>
remove `{}`

2023-06-22 15:23 UTC, MariusDoe commented on projects/bp-gallery/src/components/views/location-curating/LocationManagementDialog.tsx
> +  return position ? <Marker icon={myIcon} position={position} /> : <div></div>;
maybe replace the `div` with `null`

2023-06-22 15:23 UTC, MariusDoe commented on projects/bp-gallery/src/components/views/location-curating/LocationManagementDialog.tsx
> +      center: locationTag.coordinates ? position : new LatLng(51.8392573, 10.5279953),
Maybe put this in a named constant?

2023-06-28 20:04 UTC, MariusDoe approved these changes

2023-06-28 21:03 UTC, merged